name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  bumpver:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build plugin
        uses: ./.github/actions/build-plugin
        with:
          version: ${{ inputs.version }}

      - name: Zip release artifact
        working-directory: dist
        run:
          zip ../sharkord-lava-plugin-${{ inputs.version }}.zip -r sharkord-lava-plugin

      - name: Commit version bump
        run: |
          git add package.json
          git add manifest.json
          git commit -m "chore: bump version to ${{ inputs.version }}"

      - name: Create Git tag
        run: git tag v${{ inputs.version }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          draft: true
          files: sharkord-lava-plugin-${{ inputs.version }}.zip

      - name: Push
        run: git push --atomic origin HEAD v${{ inputs.version }}
